In [1]:
import sqlite3

In [2]:
connection = sqlite3.connect(r'C:\Users\H\Sistemas\Python\Deitel\Python\CH17\sql\books.db')            #Connect to the database

In [3]:
#Viewing the authors Table's contents

In [4]:
import pandas as pd

In [5]:
pd.options.display.max_columns = 10

In [6]:
pd.read_sql(                        #Executes a SQL query and returns a DataFrame containing the query's results
    'SELECT * FROM authors',                #SQL query to execute
    connection,                             #The SQLite database's Connection object
    index_col=['id']                        #Which column should be used as the DataFrame's row indices
)

        first    last
id
1        Paul  Deitel
2      Harvey  Deitel
3       Abbey  Deitel
4         Dan   Quirk
5   Alexander    Wald

In [7]:
pd.read_sql(
    'SELECT * FROM titles',
    connection
)

         isbn                             title  edition copyright
0  0135404673     Intro to Python for CS and DS        1      2020
1  0132151006     Internet & WWW How to Program        5      2012
2  0134743350               Java How to Program       11      2018
3  0133976890                  C How to Program        8      2016
4  0133406954  Visual Basic 2012 How to Program        6      2014
5  0134601548          Visual C# How to Program        6      2017
6  0136151574         Visual C++ How to Program        2      2008
7  0134448235                C++ How to Program       10      2017
8  0134444302            Android How to Program        3      2017
9  0134289366         Android 6 for Programmers        3      2016

In [8]:
df = pd.read_sql(
    "SELECT * FROM author_ISBN",
    connection
)

In [9]:
df.head()

   id        isbn
0   1  0134289366
1   2  0134289366
2   5  0134289366
3   1  0135404673
4   2  0135404673

In [10]:
#Select queries

In [11]:
pd.read_sql(
    "SELECT first, last FROM authors",
    connection
)

       first    last
0       Paul  Deitel
1     Harvey  Deitel
2      Abbey  Deitel
3        Dan   Quirk
4  Alexander    Wald

In [12]:
pd.read_sql(
    """SELECT title, edition, copyright FROM titles
    WHERE copyright > '2016'""",
    connection
)

                           title  edition copyright
0  Intro to Python for CS and DS        1      2020
1            Java How to Program       11      2018
2       Visual C# How to Program        6      2017
3             C++ How to Program       10      2017
4         Android How to Program        3      2017

In [13]:
pd.read_sql(
    """SELECT first, last FROM authors WHERE last LIKE 'D%'""",
    connection
)

    first    last
0    Paul  Deitel
1  Harvey  Deitel
2   Abbey  Deitel

In [14]:
pd.read_sql(
    """SELECT first, last FROM authors WHERE first LIKE '_b%'""",
    connection
)

   first    last
0  Abbey  Deitel

In [15]:
pd.read_sql(
    "SELECT title from titles ORDER BY title ASC",
    connection
)

                              title
0         Android 6 for Programmers
1            Android How to Program
2                  C How to Program
3                C++ How to Program
4     Internet & WWW How to Program
5     Intro to Python for CS and DS
6               Java How to Program
7  Visual Basic 2012 How to Program
8          Visual C# How to Program
9         Visual C++ How to Program

In [17]:
pd.read_sql(
    "SELECT id, first, last FROM authors ORDER BY last, first",
    connection,
    index_col=['id']
)

        first    last
id
3       Abbey  Deitel
2      Harvey  Deitel
1        Paul  Deitel
4         Dan   Quirk
5   Alexander    Wald

In [18]:
pd.read_sql(
    "SELECT id, first, last FROM authors ORDER BY last DESC, first ASC",
    connection,
    index_col=['id']
)

        first    last
id
5   Alexander    Wald
4         Dan   Quirk
3       Abbey  Deitel
2      Harvey  Deitel
1        Paul  Deitel

In [20]:
pd.read_sql(
    "SELECT isbn, title, edition, copyright FROM titles WHERE title LIKE '%How to Program' ORDER BY title",
    connection
)

         isbn                             title  edition copyright
0  0134444302            Android How to Program        3      2017
1  0133976890                  C How to Program        8      2016
2  0134448235                C++ How to Program       10      2017
3  0132151006     Internet & WWW How to Program        5      2012
4  0134743350               Java How to Program       11      2018
5  0133406954  Visual Basic 2012 How to Program        6      2014
6  0134601548          Visual C# How to Program        6      2017
7  0136151574         Visual C++ How to Program        2      2008

In [24]:
pd.read_sql(
    """SELECT first, last, isbn FROM authors
        INNER JOIN author_ISBN
        ON authors.id = author_ISBN.id
        ORDER BY last, first""",
    connection
)

        first    last        isbn
0       Abbey  Deitel  0132151006
1       Abbey  Deitel  0133406954
2      Harvey  Deitel  0134289366
3      Harvey  Deitel  0135404673
4      Harvey  Deitel  0132151006
5      Harvey  Deitel  0134743350
6      Harvey  Deitel  0133976890
7      Harvey  Deitel  0133406954
8      Harvey  Deitel  0134601548
9      Harvey  Deitel  0136151574
10     Harvey  Deitel  0134448235
11     Harvey  Deitel  0134444302
12       Paul  Deitel  0134289366
13       Paul  Deitel  0135404673
14       Paul  Deitel  0132151006
15       Paul  Deitel  0134743350
16       Paul  Deitel  0133976890
17       Paul  Deitel  0133406954
18       Paul  Deitel  0134601548
19       Paul  Deitel  0136151574
20       Paul  Deitel  0134448235
21       Paul  Deitel  0134444302
22        Dan   Quirk  0136151574
23  Alexander    Wald  0134289366

In [25]:
#Insert data

In [26]:
cursor = connection.cursor()            #Access the rows

In [28]:
cursor = cursor.execute(                #Executes its SQL argument and returns the cursor
    """INSERT INTO authors(first, last) VALUES ('Sue', 'Red')"""
)

In [37]:
pd.read_sql("SELECT id, first, last FROM authors", connection, index_col=['id'] )

        first    last
id
1        Paul  Deitel
2      Harvey  Deitel
3       Abbey  Deitel
4         Dan   Quirk
5   Alexander    Wald
6         Sue     Red

In [ ]:
#UPDATE STATEMENT

In [30]:
cursor = cursor.execute(
    """UPDATE authors SET last='Black' WHERE id=7"""
)

In [33]:
cursor.rowcount             #Confirms that the UPDATE modfiied one row

1

In [34]:
#DELETE STATEMENT

In [35]:
cursor = cursor.execute('DELETE FROM authors WHERE id=7')

In [36]:
cursor.rowcount

1

In [38]:
#Close connection

In [ ]:
connection.close()