In [1]:
import pandas as pd

In [23]:
grades_dict = {'Wally': [100,98,76], 'Eva': [84,75,99], 'Sam': [94,77,90], 'Katie': [100,81,82], 'Bob': [83,65,85]}

In [26]:
grades = pd.DataFrame(grades_dict)
grades

   Wally  Eva  Sam  Katie  Bob
0    100   84   94    100   83
1     98   75   77     81   65
2     76   99   90     82   85

In [25]:
pd.DataFrame(grades_dict, index=['Test1', 'Test2', 'Test3'])

       Wally  Eva  Sam  Katie  Bob
Test1    100   84   94    100   83
Test2     98   75   77     81   65
Test3     76   99   90     82   85

In [27]:
grades.index = ['Test1','Test2','Test3']
grades

       Wally  Eva  Sam  Katie  Bob
Test1    100   84   94    100   83
Test2     98   75   77     81   65
Test3     76   99   90     82   85

In [6]:
grades['Eva']

Test1    84
Test2    75
Test3    99
Name: Eva, dtype: int64

In [7]:
grades.Wally

Test1    100
Test2     98
Test3     76
Name: Wally, dtype: int64

In [28]:
grades.loc['Test1']             #Access a row by its label

Wally    100
Eva       84
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [30]:
grades.iloc[0]

Wally    100
Eva       84
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [33]:
grades.loc['Test1':'Test3']

       Wally  Eva  Sam  Katie  Bob
Test1    100   84   94    100   83
Test2     98   75   77     81   65
Test3     76   99   90     82   85

In [34]:
grades.iloc[0:2]

       Wally  Eva  Sam  Katie  Bob
Test1    100   84   94    100   83
Test2     98   75   77     81   65

In [35]:
grades.loc[['Test1','Test3']]

       Wally  Eva  Sam  Katie  Bob
Test1    100   84   94    100   83
Test3     76   99   90     82   85

In [36]:
grades.iloc[[0,2]]

       Wally  Eva  Sam  Katie  Bob
Test1    100   84   94    100   83
Test3     76   99   90     82   85

In [38]:
grades.loc['Test1':'Test2', ['Eva', 'Katie']]

       Eva  Katie
Test1   84    100
Test2   75     81

In [39]:
grades.iloc[[0,2], 0:3]

       Wally  Eva  Sam
Test1    100   84   94
Test3     76   99   90

In [40]:
grades[grades>=90]

       Wally   Eva   Sam  Katie  Bob
Test1  100.0   NaN  94.0  100.0  NaN
Test2   98.0   NaN   NaN    NaN  NaN
Test3    NaN  99.0  90.0    NaN  NaN

In [41]:
grades[(grades>=80)&(grades<90)]

       Wally   Eva  Sam  Katie   Bob
Test1    NaN  84.0  NaN    NaN  83.0
Test2    NaN   NaN  NaN   81.0   NaN
Test3    NaN   NaN  NaN   82.0  85.0

In [18]:
grades.at['Test1','Eva']

np.int64(84)

In [19]:
grades.iat[0,0]

np.int64(100)

In [42]:
grades.at['Test1','Eva'] = 100
grades

       Wally  Eva  Sam  Katie  Bob
Test1    100  100   94    100   83
Test2     98   75   77     81   65
Test3     76   99   90     82   85

In [43]:
grades.iat[0,1] = 87
grades

       Wally  Eva  Sam  Katie  Bob
Test1    100   87   94    100   83
Test2     98   75   77     81   65
Test3     76   99   90     82   85

In [44]:
grades.describe()

            Wally   Eva        Sam       Katie        Bob
count    3.000000   3.0   3.000000    3.000000   3.000000
mean    91.333333  87.0  87.000000   87.666667  77.666667
std     13.316656  12.0   8.888194   10.692677  11.015141
min     76.000000  75.0  77.000000   81.000000  65.000000
25%     87.000000  81.0  83.500000   81.500000  74.000000
50%     98.000000  87.0  90.000000   82.000000  83.000000
75%     99.000000  93.0  92.000000   91.000000  84.000000
max    100.000000  99.0  94.000000  100.000000  85.000000

In [46]:
pd.set_option('precision', 2)
grades.describe()

OptionError: 'Pattern matched multiple keys'

In [47]:
grades.mean()

Wally    91.333333
Eva      87.000000
Sam      87.000000
Katie    87.666667
Bob      77.666667
dtype: float64

In [48]:
grades.T

       Test1  Test2  Test3
Wally    100     98     76
Eva       87     75     99
Sam       94     77     90
Katie    100     81     82
Bob       83     65     85

In [49]:
grades.T.describe()

            Test1      Test2      Test3
count    5.000000   5.000000   5.000000
mean    92.800000  79.200000  86.400000
std      7.661593  12.049896   8.677557
min     83.000000  65.000000  76.000000
25%     87.000000  75.000000  82.000000
50%     94.000000  77.000000  85.000000
75%    100.000000  81.000000  90.000000
max    100.000000  98.000000  99.000000

In [50]:
grades.T.mean()

Test1    92.8
Test2    79.2
Test3    86.4
dtype: float64

In [51]:
grades.sort_index(ascending=False)              #Sorting by indices in descending order

       Wally  Eva  Sam  Katie  Bob
Test3     76   99   90     82   85
Test2     98   75   77     81   65
Test1    100   87   94    100   83

In [52]:
grades.sort_index(axis=1)                      #Sorting by column indices (axis=1 -> sorts by row indices)

       Bob  Eva  Katie  Sam  Wally
Test1   83   87    100   94    100
Test2   65   75     81   77     98
Test3   85   99     82   90     76

In [53]:
grades.sort_values(by='Test1', axis=1, ascending=False)         #Sorting by column values

       Wally  Katie  Sam  Eva  Bob
Test1    100    100   94   87   83
Test2     98     81   77   75   65
Test3     76     82   90   99   85

In [54]:
grades.T.sort_values(by='Test1', ascending=False)

       Test1  Test2  Test3
Wally    100     98     76
Katie    100     81     82
Sam       94     77     90
Eva       87     75     99
Bob       83     65     85

In [55]:
grades.loc['Test1'].sort_values(ascending=False)

Wally    100
Katie    100
Sam       94
Eva       87
Bob       83
Name: Test1, dtype: int64